

spring:
  application:
    name: server-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Arquitectura-de-Software-02-2023/server-config

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8714/eureka/
server:
  port: 8888

encrypt:
  key: mySecretKey123456